apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: CDCI-TEST/IMAGE
  newName: mdoci/cdci-test
  newTag: 52fa6573596ad59ffede5919c40f1701b1ec38b5
