apiVersion: v1
kind: Service
metadata:
  name: cdci-test-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: cdci-test
  ports:
  - port: 2333
    protocol: TCP
    targetPort: 3000
