name: Build and publish app

on:
  push:
    branches:
    - main

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Image
        run: |-
          docker build . --tag "mikkopr/cdci-test:$GITHUB_SHA"
          docker push "mikkopr/cdci-test:$GITHUB_SHA"
      
      # Update kustomization.yaml
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2
      
      - name: Specify Image
        run: kustomize edit set image CDCI-TEST/IMAGE=mikkopr/cdci-test:$GITHUB_SHA

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: "kustomization.yaml"
          message: "Github action updates image version in kustomization."
